// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://beatzcrtqrktbdlnikig.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJlYXR6Y3J0cXJrdGJkbG5pa2lnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MDkxMzYsImV4cCI6MjA2NTM4NTEzNn0.s5aM3l-Mt-2jEGzlZIiKt0pB167w7mThcVXg1fwOUHs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);